/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.libreria.view.panels;

import com.libreria.controllers.BookController;
import com.libreria.model.entidades.Book;
import com.libreria.view.MainMenu;
import javax.swing.*;
/**
 *
 * @author pc
 */
public class BookWindow extends JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(BookWindow.class.getName());

    BookController bookController;
    Book book;
    public BookWindow() {
        initComponents();
        setLocationRelativeTo(null);
        bookController = new BookController();
        BotonVolver.addActionListener(e -> {
            new MainMenu().setVisible(true);
            dispose();
        });
        bookController = new BookController();
        mostrarRegistros();
        cargarComboBoxActualizar();
        
        

        
        
        
    }
    
    private void mostrarRegistros(){
        ListaLibros.setModel(bookController.mostrar());
    }
    private void mostrarMensajeOk(String mensaje){
        JOptionPane.showMessageDialog(this, mensaje, "Mensaje", JOptionPane.INFORMATION_MESSAGE);
    }
    private void mostrarMensajeError(String mensaje){
        JOptionPane.showMessageDialog(this, mensaje, "Mensaje", JOptionPane.ERROR_MESSAGE);
    }
    private void limpiar(){
        TextFieldNombreAñadir.setText("");
        TextFieldAutorAñadir.setText("");
        TextFieldPrecioAñadir.setText("");
        TextFieldNombreAñadir.requestFocus();
    }
    private void deshabilitarBoton(){
        BotonActualizar.setEnabled(false);
    }
    private void habilitarBoton(){
        BotonActualizar.setEnabled(true);
    }
    private void cargarComboBoxActualizar() {
        
    for(Book libro : bookController.listar()){
        
    }

    for (Book libro : bookController.listar()) {
        
    }
    


    
    
    
}
    
    
    
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlPanel = new javax.swing.JPanel();
        BotonVolver = new javax.swing.JButton();
        TituloAñadir = new javax.swing.JLabel();
        lblTitle1 = new javax.swing.JLabel();
        TextFieldNombreAñadir = new javax.swing.JTextField();
        BotonAñadir = new javax.swing.JButton();
        lblTitle4 = new javax.swing.JLabel();
        lblTitle5 = new javax.swing.JLabel();
        TextFieldAutorAñadir = new javax.swing.JTextField();
        TextFieldPrecioAñadir = new javax.swing.JTextField();
        BotonActualizar = new javax.swing.JButton();
        BotonEliminar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        ListaLibros = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Libros");
        setLocation(new java.awt.Point(0, 0));
        setMaximumSize(new java.awt.Dimension(800, 600));
        setMinimumSize(new java.awt.Dimension(800, 600));
        setPreferredSize(new java.awt.Dimension(800, 600));
        setResizable(false);

        pnlPanel.setBackground(new java.awt.Color(51, 51, 51));
        pnlPanel.setFocusable(false);
        pnlPanel.setMaximumSize(new java.awt.Dimension(800, 600));
        pnlPanel.setMinimumSize(new java.awt.Dimension(800, 600));
        pnlPanel.setPreferredSize(new java.awt.Dimension(800, 600));

        BotonVolver.setBackground(new java.awt.Color(51, 51, 51));
        BotonVolver.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        BotonVolver.setForeground(new java.awt.Color(255, 255, 255));
        BotonVolver.setText("< Volver");
        BotonVolver.setBorder(null);
        BotonVolver.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        BotonVolver.setFocusable(false);

        TituloAñadir.setBackground(new java.awt.Color(51, 51, 51));
        TituloAñadir.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        TituloAñadir.setForeground(new java.awt.Color(255, 255, 255));
        TituloAñadir.setText("Stock de Libros");
        TituloAñadir.setOpaque(true);

        lblTitle1.setBackground(new java.awt.Color(51, 51, 51));
        lblTitle1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblTitle1.setForeground(new java.awt.Color(255, 255, 255));
        lblTitle1.setText("Nombre:");
        lblTitle1.setOpaque(true);

        TextFieldNombreAñadir.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        TextFieldNombreAñadir.setBorder(javax.swing.BorderFactory.createLineBorder(null));
        TextFieldNombreAñadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextFieldNombreAñadirActionPerformed(evt);
            }
        });

        BotonAñadir.setBackground(new java.awt.Color(51, 51, 51));
        BotonAñadir.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        BotonAñadir.setForeground(new java.awt.Color(255, 255, 255));
        BotonAñadir.setText("Añadir");
        BotonAñadir.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        BotonAñadir.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        BotonAñadir.setFocusable(false);
        BotonAñadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonAñadirActionPerformed(evt);
            }
        });

        lblTitle4.setBackground(new java.awt.Color(51, 51, 51));
        lblTitle4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblTitle4.setForeground(new java.awt.Color(255, 255, 255));
        lblTitle4.setText("Autor:");
        lblTitle4.setOpaque(true);

        lblTitle5.setBackground(new java.awt.Color(51, 51, 51));
        lblTitle5.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblTitle5.setForeground(new java.awt.Color(255, 255, 255));
        lblTitle5.setText("Precio:");
        lblTitle5.setOpaque(true);

        TextFieldAutorAñadir.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        TextFieldAutorAñadir.setBorder(javax.swing.BorderFactory.createLineBorder(null));
        TextFieldAutorAñadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextFieldAutorAñadirActionPerformed(evt);
            }
        });

        TextFieldPrecioAñadir.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        TextFieldPrecioAñadir.setBorder(javax.swing.BorderFactory.createLineBorder(null));
        TextFieldPrecioAñadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextFieldPrecioAñadirActionPerformed(evt);
            }
        });

        BotonActualizar.setBackground(new java.awt.Color(51, 51, 51));
        BotonActualizar.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        BotonActualizar.setForeground(new java.awt.Color(255, 255, 255));
        BotonActualizar.setText("Actualizar");
        BotonActualizar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        BotonActualizar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        BotonActualizar.setFocusable(false);
        BotonActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonActualizarActionPerformed(evt);
            }
        });

        BotonEliminar.setBackground(new java.awt.Color(51, 51, 51));
        BotonEliminar.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        BotonEliminar.setForeground(new java.awt.Color(255, 255, 255));
        BotonEliminar.setText("Eliminar");
        BotonEliminar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        BotonEliminar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        BotonEliminar.setFocusable(false);
        BotonEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonEliminarActionPerformed(evt);
            }
        });

        ListaLibros.setBackground(new java.awt.Color(51, 51, 51));
        ListaLibros.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        ListaLibros.setForeground(new java.awt.Color(255, 255, 255));
        ListaLibros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Nombre", "Autor", "Precio"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        ListaLibros.setFocusable(false);
        ListaLibros.getTableHeader().setResizingAllowed(false);
        ListaLibros.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(ListaLibros);
        if (ListaLibros.getColumnModel().getColumnCount() > 0) {
            ListaLibros.getColumnModel().getColumn(0).setPreferredWidth(100);
            ListaLibros.getColumnModel().getColumn(1).setResizable(false);
            ListaLibros.getColumnModel().getColumn(2).setResizable(false);
            ListaLibros.getColumnModel().getColumn(3).setResizable(false);
        }

        javax.swing.GroupLayout pnlPanelLayout = new javax.swing.GroupLayout(pnlPanel);
        pnlPanel.setLayout(pnlPanelLayout);
        pnlPanelLayout.setHorizontalGroup(
            pnlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPanelLayout.createSequentialGroup()
                .addGroup(pnlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(pnlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlPanelLayout.createSequentialGroup()
                                .addGroup(pnlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblTitle5, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblTitle4, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblTitle1))
                                .addGap(25, 25, 25)
                                .addGroup(pnlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(TextFieldPrecioAñadir)
                                    .addComponent(TextFieldAutorAñadir)
                                    .addComponent(TextFieldNombreAñadir, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(TituloAñadir)
                            .addComponent(BotonVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pnlPanelLayout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addComponent(BotonAñadir, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(BotonActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(BotonEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(pnlPanelLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 753, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        pnlPanelLayout.setVerticalGroup(
            pnlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BotonVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TituloAñadir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlPanelLayout.createSequentialGroup()
                        .addComponent(lblTitle1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblTitle4, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblTitle5, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(17, 17, 17)
                        .addGroup(pnlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BotonAñadir, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BotonActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BotonEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pnlPanelLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(TextFieldAutorAñadir, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TextFieldPrecioAñadir, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(TextFieldNombreAñadir, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(64, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TextFieldNombreAñadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextFieldNombreAñadirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextFieldNombreAñadirActionPerformed

    private void TextFieldAutorAñadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextFieldAutorAñadirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextFieldAutorAñadirActionPerformed

    private void TextFieldPrecioAñadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextFieldPrecioAñadirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextFieldPrecioAñadirActionPerformed

    private void BotonAñadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonAñadirActionPerformed
        
    }//GEN-LAST:event_BotonAñadirActionPerformed

    private void BotonActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonActualizarActionPerformed
        
    }//GEN-LAST:event_BotonActualizarActionPerformed

    private void BotonEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonEliminarActionPerformed
        
    }//GEN-LAST:event_BotonEliminarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new BookWindow().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonActualizar;
    private javax.swing.JButton BotonAñadir;
    private javax.swing.JButton BotonEliminar;
    private javax.swing.JButton BotonVolver;
    private javax.swing.JTable ListaLibros;
    private javax.swing.JTextField TextFieldAutorAñadir;
    private javax.swing.JTextField TextFieldNombreAñadir;
    private javax.swing.JTextField TextFieldPrecioAñadir;
    private javax.swing.JLabel TituloAñadir;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTitle1;
    private javax.swing.JLabel lblTitle4;
    private javax.swing.JLabel lblTitle5;
    private javax.swing.JPanel pnlPanel;
    // End of variables declaration//GEN-END:variables
}
