/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.libreria.view.panels;

import com.libreria.view.MainMenu;
import javax.swing.*;
/**
 *
 * @author pc
 */
public class SaleWindow extends JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(SaleWindow.class.getName());

    /**
     * Creates new form SaleWindow
     */
    public SaleWindow() {
        initComponents();
        
        btnBackMenu.addActionListener(e -> {
            new MainMenu().setVisible(true);
            dispose();
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlPanel = new javax.swing.JPanel();
        btnBackMenu = new javax.swing.JButton();
        TituloAñadir = new javax.swing.JLabel();
        lblTitle1 = new javax.swing.JLabel();
        BotonAñadir = new javax.swing.JButton();
        lblTitle4 = new javax.swing.JLabel();
        lblTitle5 = new javax.swing.JLabel();
        TextFieldAutorAñadir = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        ListaLibros = new javax.swing.JTable();
        BotonAñadir1 = new javax.swing.JButton();
        BotonAñadir2 = new javax.swing.JButton();
        lblTitle6 = new javax.swing.JLabel();
        TextFieldAutorAñadir1 = new javax.swing.JTextField();
        TextFieldAutorAñadir2 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Ventas");
        setLocation(new java.awt.Point(550, 240));
        setMinimumSize(new java.awt.Dimension(600, 600));
        setResizable(false);

        pnlPanel.setBackground(new java.awt.Color(51, 51, 51));
        pnlPanel.setPreferredSize(new java.awt.Dimension(600, 600));

        btnBackMenu.setBackground(new java.awt.Color(51, 51, 51));
        btnBackMenu.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnBackMenu.setForeground(new java.awt.Color(255, 255, 255));
        btnBackMenu.setText("< Volver");
        btnBackMenu.setBorder(null);
        btnBackMenu.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnBackMenu.setFocusable(false);

        TituloAñadir.setBackground(new java.awt.Color(51, 51, 51));
        TituloAñadir.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        TituloAñadir.setForeground(new java.awt.Color(255, 255, 255));
        TituloAñadir.setText("Ventas");
        TituloAñadir.setOpaque(true);

        lblTitle1.setBackground(new java.awt.Color(51, 51, 51));
        lblTitle1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblTitle1.setForeground(new java.awt.Color(255, 255, 255));
        lblTitle1.setText("Cliente:");
        lblTitle1.setOpaque(true);

        BotonAñadir.setBackground(new java.awt.Color(51, 51, 51));
        BotonAñadir.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        BotonAñadir.setForeground(new java.awt.Color(255, 255, 255));
        BotonAñadir.setText("Añadir");
        BotonAñadir.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        BotonAñadir.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        BotonAñadir.setFocusable(false);
        BotonAñadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonAñadirActionPerformed(evt);
            }
        });

        lblTitle4.setBackground(new java.awt.Color(51, 51, 51));
        lblTitle4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblTitle4.setForeground(new java.awt.Color(255, 255, 255));
        lblTitle4.setText("Cantidad de libros:");
        lblTitle4.setOpaque(true);

        lblTitle5.setBackground(new java.awt.Color(51, 51, 51));
        lblTitle5.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblTitle5.setForeground(new java.awt.Color(255, 255, 255));
        lblTitle5.setText("Monto total:");
        lblTitle5.setOpaque(true);

        TextFieldAutorAñadir.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        TextFieldAutorAñadir.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        TextFieldAutorAñadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextFieldAutorAñadirActionPerformed(evt);
            }
        });

        ListaLibros.setBackground(new java.awt.Color(51, 51, 51));
        ListaLibros.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        ListaLibros.setForeground(new java.awt.Color(255, 255, 255));
        ListaLibros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Cliente", "Cant. libros", "Monto total", "Fecha"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        ListaLibros.setFocusable(false);
        ListaLibros.getTableHeader().setResizingAllowed(false);
        ListaLibros.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(ListaLibros);
        if (ListaLibros.getColumnModel().getColumnCount() > 0) {
            ListaLibros.getColumnModel().getColumn(0).setResizable(false);
            ListaLibros.getColumnModel().getColumn(0).setPreferredWidth(1);
            ListaLibros.getColumnModel().getColumn(1).setResizable(false);
            ListaLibros.getColumnModel().getColumn(2).setResizable(false);
            ListaLibros.getColumnModel().getColumn(3).setResizable(false);
            ListaLibros.getColumnModel().getColumn(3).setPreferredWidth(1);
            ListaLibros.getColumnModel().getColumn(4).setResizable(false);
            ListaLibros.getColumnModel().getColumn(4).setPreferredWidth(1);
        }

        BotonAñadir1.setBackground(new java.awt.Color(51, 51, 51));
        BotonAñadir1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        BotonAñadir1.setForeground(new java.awt.Color(255, 255, 255));
        BotonAñadir1.setText("Modificar");
        BotonAñadir1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        BotonAñadir1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        BotonAñadir1.setFocusable(false);
        BotonAñadir1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonAñadir1ActionPerformed(evt);
            }
        });

        BotonAñadir2.setBackground(new java.awt.Color(51, 51, 51));
        BotonAñadir2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        BotonAñadir2.setForeground(new java.awt.Color(255, 255, 255));
        BotonAñadir2.setText("Eliminar");
        BotonAñadir2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        BotonAñadir2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        BotonAñadir2.setFocusable(false);
        BotonAñadir2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonAñadir2ActionPerformed(evt);
            }
        });

        lblTitle6.setBackground(new java.awt.Color(51, 51, 51));
        lblTitle6.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblTitle6.setForeground(new java.awt.Color(255, 255, 255));
        lblTitle6.setText("Fecha:");
        lblTitle6.setOpaque(true);

        TextFieldAutorAñadir1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        TextFieldAutorAñadir1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        TextFieldAutorAñadir1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextFieldAutorAñadir1ActionPerformed(evt);
            }
        });

        TextFieldAutorAñadir2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        TextFieldAutorAñadir2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        TextFieldAutorAñadir2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextFieldAutorAñadir2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlPanelLayout = new javax.swing.GroupLayout(pnlPanel);
        pnlPanel.setLayout(pnlPanelLayout);
        pnlPanelLayout.setHorizontalGroup(
            pnlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnBackMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 571, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TituloAñadir)
                    .addComponent(lblTitle6, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlPanelLayout.createSequentialGroup()
                        .addGroup(pnlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lblTitle5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblTitle1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblTitle4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TextFieldAutorAñadir, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TextFieldAutorAñadir1, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TextFieldAutorAñadir2, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BotonAñadir, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BotonAñadir1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BotonAñadir2, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(76, 76, 76))
        );
        pnlPanelLayout.setVerticalGroup(
            pnlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnBackMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TituloAñadir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTitle1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TextFieldAutorAñadir2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlPanelLayout.createSequentialGroup()
                        .addGroup(pnlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblTitle4, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TextFieldAutorAñadir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(9, 9, 9)
                        .addComponent(lblTitle5, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(TextFieldAutorAñadir1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTitle6, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addGroup(pnlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BotonAñadir)
                    .addComponent(BotonAñadir1)
                    .addComponent(BotonAñadir2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 331, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 583, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotonAñadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonAñadirActionPerformed
        
    }//GEN-LAST:event_BotonAñadirActionPerformed

    private void TextFieldAutorAñadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextFieldAutorAñadirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextFieldAutorAñadirActionPerformed

    private void BotonAñadir1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonAñadir1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotonAñadir1ActionPerformed

    private void BotonAñadir2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonAñadir2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotonAñadir2ActionPerformed

    private void TextFieldAutorAñadir1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextFieldAutorAñadir1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextFieldAutorAñadir1ActionPerformed

    private void TextFieldAutorAñadir2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextFieldAutorAñadir2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextFieldAutorAñadir2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new SaleWindow().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonAñadir;
    private javax.swing.JButton BotonAñadir1;
    private javax.swing.JButton BotonAñadir2;
    private javax.swing.JTable ListaLibros;
    private javax.swing.JTextField TextFieldAutorAñadir;
    private javax.swing.JTextField TextFieldAutorAñadir1;
    private javax.swing.JTextField TextFieldAutorAñadir2;
    private javax.swing.JLabel TituloAñadir;
    private javax.swing.JButton btnBackMenu;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTitle1;
    private javax.swing.JLabel lblTitle4;
    private javax.swing.JLabel lblTitle5;
    private javax.swing.JLabel lblTitle6;
    private javax.swing.JPanel pnlPanel;
    // End of variables declaration//GEN-END:variables
}
